name: place_tracker
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: "<4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  google_maps_flutter: ^2.0.0
  uuid: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.7.0

flutter:
  assets:
    - assets/

  uses-material-design: true
