name: particle_background
description: Example for the simple_animations package
author: Felix Blaschke <felix@felix-blaschke.de>
homepage: https://github.com/felixblaschke/simple_animations

environment:
  sdk: "<4.0.0"

dependencies:
  flutter:
    sdk: flutter
flutter:
  assets:
    - preview.png
